[package]
name = "letterboxd-list-sync"
version = "0.1.0"
authors = ["karsten"]

[dependencies]
docopt = "0.8"
futures = "0.1"
# letterboxd = { git = "https://github.com/boxdot/letterboxd-rs.git" }
letterboxd = { path = "../letterboxd-rs" }
regex = "0.2"
serde = "1.0"
serde_derive = "1.0"
tokio-core = "0.1"
