[package]
name = "letterboxd-list-sync"
version = "0.1.0"
authors = ["karsten"]

[dependencies]
docopt = "0.8"
futures = "0.1"
letterboxd = { path = "../letterboxd-rs" }
# letterboxd = "0.1"
regex = "0.2"
serde = "1.0"
serde_derive = "1.0"
tokio-core = "0.1"
